export default (app) => {
  app.post(
    `/tenant/:tenantId/questionario-pergunta`,
    require('./questionarioPerguntaCreate').default,
  );
  app.put(
    `/tenant/:tenantId/questionario-pergunta/:id`,
    require('./questionarioPerguntaUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/questionario-pergunta/import`,
    require('./questionarioPerguntaImport').default,
  );
  app.delete(
    `/tenant/:tenantId/questionario-pergunta`,
    require('./questionarioPerguntaDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/questionario-pergunta/autocomplete`,
    require('./questionarioPerguntaAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/questionario-pergunta`,
    require('./questionarioPerguntaList').default,
  );
  app.get(
    `/tenant/:tenantId/questionario-pergunta/:id`,
    require('./questionarioPerguntaFind').default,
  );
  app.get(
    `/questionario-open-listar`,
    require('./questionarioPerguntaListOpen').default,
  );
};
