export default (app) => {
  app.post(
    `/tenant/:tenantId/programa-atividade`,
    require('./programaAtividadeCreate').default,
  );
  app.put(
    `/tenant/:tenantId/programa-atividade/:id`,
    require('./programaAtividadeUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/programa-atividade/import`,
    require('./programaAtividadeImport').default,
  );
  app.delete(
    `/tenant/:tenantId/programa-atividade`,
    require('./programaAtividadeDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/programa-atividade/autocomplete`,
    require('./programaAtividadeAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/programa-atividade`,
    require('./programaAtividadeList').default,
  );
  app.get(
    `/tenant/:tenantId/programa-atividade/:id`,
    require('./programaAtividadeFind').default,
  );
};
