export default (app) => {
  app.post(
    `/tenant/:tenantId/questionario-cliente-resposta`,
    require('./questionarioClienteRespostaCreate').default,
  );
  app.put(
    `/tenant/:tenantId/questionario-cliente-resposta/:id`,
    require('./questionarioClienteRespostaUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/questionario-cliente-resposta/import`,
    require('./questionarioClienteRespostaImport').default,
  );
  app.delete(
    `/tenant/:tenantId/questionario-cliente-resposta`,
    require('./questionarioClienteRespostaDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/questionario-cliente-resposta/autocomplete`,
    require('./questionarioClienteRespostaAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/questionario-cliente-resposta`,
    require('./questionarioClienteRespostaList').default,
  );
  app.get(
    `/tenant/:tenantId/questionario-cliente-resposta/:id`,
    require('./questionarioClienteRespostaFind').default,
  );
  app.get(
    `/questionario-open-resposta-list`,
    require('./questionarioClienteRespostaListOpen').default,
  );
  app.post(
    `/questionario-open-criar`,
    require('./questionarioCriar').default,
  );
  app.put(
    `/tenant/:tenantId/questionario-resposta/:id`,
    require('./questionarioClienteRespostaUpdate').default,
  );
  
  app.delete(
    `/questionario-open-deletar`,
    require('./questionarioClienteRespostaDestroyOpen').default,
  );
};
