export default (app) => {
  app.post(
    `/tenant/:tenantId/curso-cliente`,
    require('./cursoClienteCreate').default,
  );
  app.put(
    `/tenant/:tenantId/curso-cliente/:id`,
    require('./cursoClienteUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/curso-cliente/import`,
    require('./cursoClienteImport').default,
  );
  app.delete(
    `/tenant/:tenantId/curso-cliente`,
    require('./cursoClienteDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/curso-cliente/autocomplete`,
    require('./cursoClienteAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/curso-cliente`,
    require('./cursoClienteList').default,
  );
  app.get(
    `/tenant/:tenantId/curso-cliente/:id`,
    require('./cursoClienteFind').default,
  );

//Rotas App

  app.post(
    `/app/cliente/:id/:token/curso-cliente/`,
    require('./appCursoClienteCreate').default,
  );
  app.get(
    `/app/cliente/:id/:token/curso-cliente`,
    require('./appCursoClienteList').default,
  );
  app.get(
    `/app/cliente/:id/:token/curso-cliente/:curso`,
    require('./appCursoClienteFind').default,
  );
  app.get(
    `/app/cliente/:id/:token/curso/ultimo`,
    require('./appCursoClienteUltimoAdquirido').default,
  );
  app.get(
    `/curso-cliente/rotina`,
    require('./cursoClienteRotina').default,
  );
};
