export default (app) => {
  app.post(
    `/tenant/:tenantId/questionario`,
    require('./questionarioCreate').default,
  );
  app.put(
    `/tenant/:tenantId/questionario/:id`,
    require('./questionarioUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/questionario/import`,
    require('./questionarioImport').default,
  );
  app.delete(
    `/tenant/:tenantId/questionario`,
    require('./questionarioDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/questionario/autocomplete`,
    require('./questionarioAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/questionario`,
    require('./questionarioList').default,
  );
  app.get(
    `/tenant/:tenantId/questionario/:id`,
    require('./questionarioFind').default,
  );
  app.get(
    `/questionario-open/:id`,
    require('./questionarioFindOpen').default,
  );
};
