export default (app) => {
  app.post(
    `/tenant/:tenantId/programa`,
    require('./programaCreate').default,
  );
  app.put(
    `/tenant/:tenantId/programa/:id`,
    require('./programaUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/programa/import`,
    require('./programaImport').default,
  );
  app.delete(
    `/tenant/:tenantId/programa`,
    require('./programaDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/programa/autocomplete`,
    require('./programaAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/programa`,
    require('./programaList').default,
  );
  app.get(
    `/tenant/:tenantId/programa/:id`,
    require('./programaFind').default,
  );
};
