export default (app) => {
  app.post(
    `/tenant/:tenantId/plano-cliente`,
    require('./planoClienteCreate').default,
  );
  app.put(
    `/tenant/:tenantId/plano-cliente/:id`,
    require('./planoClienteUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/plano-cliente/import`,
    require('./planoClienteImport').default,
  );
  app.delete(
    `/tenant/:tenantId/plano-cliente`,
    require('./planoClienteDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/plano-cliente/autocomplete`,
    require('./planoClienteAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/plano-cliente`,
    require('./planoClienteList').default,
  );
  app.get(
    `/tenant/:tenantId/plano-cliente/:id`,
    require('./planoClienteFind').default,
  );
};
