export default (app) => {
  app.post(
    `/tenant/:tenantId/questionario-cliente`,
    require('./questionarioClienteCreate').default,
  );
  app.put(
    `/tenant/:tenantId/questionario-cliente/:id`,
    require('./questionarioClienteUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/questionario-cliente/import`,
    require('./questionarioClienteImport').default,
  );
  app.delete(
    `/tenant/:tenantId/questionario-cliente`,
    require('./questionarioClienteDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/questionario-cliente/autocomplete`,
    require('./questionarioClienteAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/questionario-cliente`,
    require('./questionarioClienteList').default,
  );
  app.get(
    `/tenant/:tenantId/questionario-cliente/:id`,
    require('./questionarioClienteFind').default,
  ); 
  app.get(
    `/questionario-open`,
    require('./questionarioClienteListOpen').default,
  );
  app.post(
    `/questionario-open`,
    require('./questionarioClienteCreateOpen').default,
  );
  app.get(
    `/questionario-cliente/:id/:avaliacao`,
    require('./questionarioClienteFindByCliente').default,
  );
};
