export default (app) => {
  app.post(
    `/tenant/:tenantId/regiao`,
    require('./regiaoCreate').default,
  );
  app.put(
    `/tenant/:tenantId/regiao/:id`,
    require('./regiaoUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/regiao/import`,
    require('./regiaoImport').default,
  );
  app.delete(
    `/tenant/:tenantId/regiao`,
    require('./regiaoDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/regiao/autocomplete`,
    require('./regiaoAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/regiao`,
    require('./regiaoList').default,
  );
  app.get(
    `/tenant/:tenantId/regiao/:id`,
    require('./regiaoFind').default,
  );
};
