export default (app) => {
  app.post(
    `/tenant/:tenantId/questionario-tipo`,
    require('./questionarioTipoCreate').default,
  );
  app.put(
    `/tenant/:tenantId/questionario-tipo/:id`,
    require('./questionarioTipoUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/questionario-tipo/import`,
    require('./questionarioTipoImport').default,
  );
  app.delete(
    `/tenant/:tenantId/questionario-tipo`,
    require('./questionarioTipoDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/questionario-tipo/autocomplete`,
    require('./questionarioTipoAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/questionario-tipo`,
    require('./questionarioTipoList').default,
  );
  app.get(
    `/tenant/:tenantId/questionario-tipo/:id`,
    require('./questionarioTipoFind').default,
  );
};
