export default (app) => {
  app.post(
    `/tenant/:tenantId/curso-cliente-aula`,
    require('./cursoClienteAulaCreate').default,
  );
  app.put(
    `/tenant/:tenantId/curso-cliente-aula/:id`,
    require('./cursoClienteAulaUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/curso-cliente-aula/import`,
    require('./cursoClienteAulaImport').default,
  );
  app.delete(
    `/tenant/:tenantId/curso-cliente-aula`,
    require('./cursoClienteAulaDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/curso-cliente-aula/autocomplete`,
    require('./cursoClienteAulaAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/curso-cliente-aula`,
    require('./cursoClienteAulaList').default,
  );
  app.get(
    `/tenant/:tenantId/curso-cliente-aula/:id`,
    require('./cursoClienteAulaFind').default,
  );
};
